FROM node:20-alpine as base

RUN addgroup -S appgroup && adduser -S app -G appgroup
USER app

WORKDIR /app
COPY package.json ./
RUN npm install

COPY --chown=app:app . /app
CMD npx next dev -H client -p $CLIENT_PORT